const tabelaBrasil = [
  {
    nome: "Athletico-PR",
    sigla: "CAP",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "São Paulo",
    sigla: "SAO",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Palmeiras",
    sigla: "PAl",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Flamengo",
    sigla: "FLA",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Corinthians",
    sigla: "COR",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Santos",
    sigla: "SAN",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Mirassol",
    sigla: "MIR",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Bragantino",
    sigla: "BRA",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Vasco",
    sigla: "VAS",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Fluminense",
    sigla: "FLU",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Botafogo",
    sigla: "BOT",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Grêmio",
    sigla: "GRE",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Internacional",
    sigla: "INT",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Coritiba",
    sigla: "CFC",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Cruzeiro",
    sigla: "CRU",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Atletico-MG",
    sigla: "CAM",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Chapecoense",
    sigla: "CHA",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Bahia",
    sigla: "BAH",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Vitoria",
    sigla: "VIT",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: "Remo",
    sigla: "REM",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
];

export default tabelaBrasil;

